-- Noor Community MVP schema
-- Enable Anonymous Sign-Ins in Supabase Authentication before using this.

create table if not exists public.community_posts (
  id uuid primary key default gen_random_uuid(),
  author_user_id uuid not null,
  author_name text not null check (char_length(author_name) between 1 and 30),
  topic text not null check (topic in ('General','Quran','Prayer','Ramadan & Events','Local & Mosques','Learning')),
  title text not null check (char_length(title) between 1 and 90),
  body text not null check (char_length(body) between 1 and 1200),
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  post_id uuid references public.community_posts(id) on delete cascade,
  reporter_user_id uuid not null,
  reason text not null default 'user_report',
  created_at timestamptz not null default now(),
  unique (post_id, reporter_user_id)
);

alter table public.community_posts enable row level security;
alter table public.community_reports enable row level security;

create policy "community posts readable when public and not hidden"
on public.community_posts for select
using (hidden = false);

create policy "authenticated anonymous users can create posts"
on public.community_posts for insert
to authenticated
with check (author_user_id = auth.uid());

create policy "users can submit reports"
on public.community_reports for insert
to authenticated
with check (reporter_user_id = auth.uid());

create index if not exists community_posts_created_at_idx on public.community_posts(created_at desc);
create index if not exists community_posts_topic_idx on public.community_posts(topic);
create index if not exists community_reports_post_id_idx on public.community_reports(post_id);


-- Server-side anti-spam guard; client-side limits alone can be bypassed.
create or replace function public.noor_enforce_post_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare recent_count integer;
begin
  select count(*) into recent_count from public.community_posts where author_user_id = new.author_user_id and created_at > now() - interval '1 hour';
  if recent_count >= 10 then raise exception 'posting rate limit reached'; end if;
  return new;
end;
$$;
drop trigger if exists noor_post_rate_limit on public.community_posts;
create trigger noor_post_rate_limit before insert on public.community_posts for each row execute function public.noor_enforce_post_rate_limit();
